name: podvader
services:
  hugo:
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    image: ghcr.io/hugomods/hugo:0.159.1@sha256:9adabca736765ff2320aeceae26388f9cabf356307adfac89f9403a2666fb5c3
    command: hugo server --bind 0.0.0.0 -D --minify --gc
