name: podvader
services:
  hugo:
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    image: ghcr.io/hugomods/hugo:0.159.2@sha256:6068880c6d71da481db38a5b760ee5e75de5c96d499e66ea6c6d4f6bcbcfdf3b
    command: hugo server --bind 0.0.0.0 -D --minify --gc
