name: podvader
services:
  hugo:
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    image: ghcr.io/hugomods/hugo:0.163.3@sha256:367ea85950c9f3e12746fbf049f29ea00758c86791072dfdc9772748ff9306bc
    command: hugo server --bind 0.0.0.0 -D --minify --gc
