name: Multiarch-build

on:
  push:
    branches:
      - main
    paths:
      - "bind9/**"
  pull_request:
    branches:
      - main
    paths:
      - "bind9/**"

jobs:
  get-version-from-package:
    uses: npastorale/workflows/.github/workflows/release-version-from-package.yaml@main
    with:
      package-name: bind

  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    needs: get-version-from-package
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      release-version: ${{ needs.get-version-from-package.outputs.release-version }}
    secrets:
      access-token: ${{ secrets.docker_token }}
