name: Bind9 build

on:
  push:
    paths:
      - "bind9/**"
  pull_request:
    paths:
      - "bind9/**"

jobs:
  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      image: bind
      package: bind
      dockerfile: bind9/Dockerfile
    secrets:
      access-token: ${{ secrets.docker_token }}
