name: Multiarch-build

on:
  push:
    paths:
      - "kubectl/**"

jobs:
  get-version-from-package:
    uses: npastorale/workflows/.github/workflows/release-version-from-package.yaml@main
    with:
      package-name: kubectl

  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    needs: get-version-from-package
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      release-version: ${{ needs.get-version-from-package.outputs.release-version }}
      file: kubectl/Dockerfile
    secrets:
      access-token: ${{ secrets.docker_token }}
