name: Kubectl build

on:
  push:
    paths:
      - "kubectl/**"
  pull_request:
    paths:
      - "kubectl/**"

jobs:
  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      image: kubectl
      package: kubectl
      dockerfile: kubectl/Dockerfile
    secrets:
      access-token: ${{ secrets.docker_token }}
