name: Multiarch-build

on:
  push:
    paths:
      - "podvader/**"
  pull_request:
    paths:
      - "podvader/**"

jobs:
  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      image: podvader
      package: podvader
      dockerfile: podvader/Dockerfile
      checkout_submodules: true
    secrets:
      access-token: ${{ secrets.docker_token }}
