name: Rsync build

on:
  push:
    paths:
      - "rsync/**"
  pull_request:
    paths:
      - "rsync/**"

jobs:
  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      image: rsync
      package: rsync
      dockerfile: rsync/Dockerfile
    secrets:
      access-token: ${{ secrets.docker_token }}
