name: Multiarch-build

on:
  push:
    paths:
      - "rsync/**"
  pull_request:
    paths:
      - "rsync/**"

jobs:
  get-version-from-package:
    uses: npastorale/workflows/.github/workflows/release-version-from-package.yaml@main
    with:
      package-name: rsync
      dockerfile: rsync/Dockerfile

  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    needs: get-version-from-package
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      image: rsync
      release-version: ${{ needs.get-version-from-package.outputs.release-version }}
      dockerfile: rsync/Dockerfile
    secrets:
      access-token: ${{ secrets.docker_token }}
